---
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  # Load packages
  packages: !include_dir_named integrations

  # metric for Metric, imperial for Imperial
  # unit_system: metric
  # Pick yours from here:
  # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  # time_zone: Europe/London
  # Customization file
  customize: !include_dir_named customizations

group: !include groups.yaml
scene: !include scenes.yaml
